CREATE TABLE tb_messages (

	id				INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	texto			VARCHAR(140) NOT NULL,
	autor 			VARCHAR(50) NOT NULL,
	create_at		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified_at		TIMESTAMP NULL DEFAULT NULL

)DEFAULT CHARACTER SET UTF8 ENGINE=InnoDB;

CREATE TABLE tb_authors (

	id 				INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	email			VARCHAR(100) NOT NULL,
	password 		VARCHAR(100) NOT NULL

)DEFAULT CHARACTER SET UTF8 ENGINE=InnoDB;